// src/components/utils/rewardsData.js
export const rewardsData = [
    {
        id: 1,
        type: "Beginner",
        title: "First Spin",
        description: "Complete your first spin.",
        reward: 10,
        unit: "points",
        unlocked: true,
    },
    {
        id: 2,
        type: "Spin Count",
        title: "Daily Spinner",
        description: "Spin the wheel 7 consecutive days.",
        reward: 50,
        unit: "points",
        unlocked: false,
    },
    {
        id: 3,
        type: "Luck-Based",
        title: "Jackpot Hunter",
        description: "Hit the ₹100 jackpot for the first time.",
        reward: 200,
        unit: "points",
        unlocked: false,
    },
    {
        id: 4,
        type: "High Roller",
        title: "Big Winner",
        description: "Win a total of ₹10,000 from the game.",
        reward: 1000,
        unit: "points",
        unlocked: false,
    },
    {
        id: 5,
        type: "Social",
        title: "Referral Master",
        description: "Refer 5 friends who each complete their first spin.",
        reward: 500,
        unit: "points",
        unlocked: false,
    },
    {
        id: 6,
        type: "Streak",
        title: "Unstoppable",
        description: "Spin the wheel every day for 14 days in a row.",
        reward: 200,
        unit: "points",
        unlocked: false,
    },
    {
        id: 7,
        type: "Milestone",
        title: "Century Club",
        description: "Win a total of 100 spins.",
        reward: 300,
        unit: "points",
        unlocked: true,
    },
    {
        id: 8,
        type: "Milestone",
        title: "Half-Century Club",
        description: "Win a total of 50 spins.",
        reward: 150,
        unit: "points",
        unlocked: true,
    },
    {
        id: 9,
        type: "Consistency",
        title: "Regular Spinner",
        description: "Spin the wheel every day for 30 days.",
        reward: 500,
        unit: "points",
        unlocked: false,
    },
    {
        id: 10,
        type: "High Roller",
        title: "Mega Winner",
        description: "Win a total of ₹50,000 from the game.",
        reward: 5000,
        unit: "points",
        unlocked: false,
    },
    {
        id: 11,
        type: "Social",
        title: "Super Referral Master",
        description: "Refer 10 friends who each complete their first spin.",
        reward: 1000,
        unit: "points",
        unlocked: false,
    },
    {
        id: 12,
        type: "Streak",
        title: "Unbreakable",
        description: "Spin the wheel every day for 60 days in a row.",
        reward: 1000,
        unit: "points",
        unlocked: false,
    },
    {
        id: 13,
        type: "Milestone",
        title: "Spin Master",
        description: "Win a total of 200 spins.",
        reward: 600,
        unit: "points",
        unlocked: false,
    },
    {
        id: 14,
        type: "Consistency",
        title: "Dedicated Spinner",
        description: "Spin the wheel every day for 90 days.",
        reward: 1500,
        unit: "points",
        unlocked: false,
    },
    {
        id: 15,
        type: "High Roller",
        title: "Ultimate Winner",
        description: "Win a total of ₹100,000 from the game.",
        reward: 10000,
        unit: "points",
        unlocked: false,
    },
    {
        id: 16,
        type: "Social",
        title: "Referral Legend",
        description: "Refer 20 friends who each complete their first spin.",
        reward: 2000,
        unit: "points",
        unlocked: false,
    },
    {
        id: 17,
        type: "Streak",
        title: "Invincible",
        description: "Spin the wheel every day for 120 days in a row.",
        reward: 2000,
        unit: "points",
        unlocked: false,
    }
];
